# Generated by Django 5.0.1 on 2024-01-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourse',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studentcourse',
            old_name='student_id',
            new_name='student',
        ),
    ]
